version: '3'
services:
   goodchain-server:
     build: .
     container_name: goodchain-server
     restart: always
     ports:
       - "5068:5068"
     volumes:
       - "./data:/app/data"
     environment:
        - PYTHONUNBUFFERED=1
     network_mode: bridge